=== hibernate/hibernate-validator/engine/src/main/xsd/validation-configuration-3.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Jakarta Validation API
  ~
  ~ License: Apache License, Version 2.0
  ~ See the license.txt file in the root directory or <http://www.apache.org/licenses/LICENSE-2.0>.
  -->
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="https://jakarta.ee/xml/ns/validation/configuration"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:config="https://jakarta.ee/xml/ns/validation/configuration"
           version="3.0">

    <xs:annotation>
        <xs:documentation><![CDATA[
            This is the XML Schema for the Jakarta Validation configuration file.
            The configuration file must be named "META-INF/validation.xml".

            Jakarta Validation configuration files must indicate the Jakarta Validation
            XML schema by using the validation namespace:

            https://jakarta.ee/xml/ns/validation/configuration

            and indicate the version of the schema by using the version attribute
            as shown below:

            <validation-config
                xmlns="https://jakarta.ee/xml/ns/validation/configuration"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="
                    https://jakarta.ee/xml/ns/validation/configuration
                    https://jakarta.ee/xml/ns/validation/validation-configuration-3.0.xsd"
                version="3.0">
                [...]
            </validation-config>
        ]]>
        </xs:documentation>
    </xs:annotation>

    <xs:element name="validation-config" type="config:validation-configType"/>
    <xs:complexType name="validation-configType">
        <xs:sequence>
            <xs:element type="xs:string" name="default-provider" minOccurs="0"/>
            <xs:element type="xs:string" name="message-interpolator" minOccurs="0"/>
            <xs:element type="xs:string" name="traversable-resolver" minOccurs="0"/>
            <xs:element type="xs:string" name="constraint-validator-factory" minOccurs="0"/>
            <xs:element type="xs:string" name="parameter-name-provider" minOccurs="0"/>
            <xs:element type="xs:string" name="clock-provider" minOccurs="0"/>
            <xs:element type="xs:string" name="value-extractor" maxOccurs="unbounded"
                    minOccurs="0"/>
            <xs:element type="config:executable-validationType" name="executable-validation"
                    minOccurs="0"/>
            <xs:element type="xs:string" name="constraint-mapping" maxOccurs="unbounded"
                    minOccurs="0"/>
            <xs:element type="config:propertyType" name="property" maxOccurs="unbounded"
                    minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="version" type="config:versionType" fixed="3.0" use="required"/>
    </xs:complexType>

    <xs:complexType name="executable-validationType">
        <xs:sequence>
            <xs:element type="config:default-validated-executable-typesType"
                    name="default-validated-executable-types" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="enabled" use="optional" type="xs:boolean" default="true"/>
    </xs:complexType>
    <xs:complexType name="default-validated-executable-typesType">
        <xs:sequence>
            <xs:element name="executable-type" maxOccurs="unbounded" minOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="NONE"/>
                        <xs:enumeration value="CONSTRUCTORS"/>
                        <xs:enumeration value="NON_GETTER_METHODS"/>
                        <xs:enumeration value="GETTER_METHODS"/>
                        <xs:enumeration value="ALL"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="propertyType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" use="required" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="versionType">
        <xs:restriction base="xs:token">
            <xs:pattern value="[0-9]+(\.[0-9]+)*" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== hibernate/hibernate-validator/documentation/src/test/resources/org/hibernate/validator/referenceguide/chapter08/validation.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
	SPDX-License-Identifier: Apache-2.0
	Copyright Red Hat Inc. and Hibernate Authors
-->
<validation-config
		xmlns="https://jakarta.ee/xml/ns/validation/configuration"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="https://jakarta.ee/xml/ns/validation/configuration
			https://jakarta.ee/xml/ns/validation/validation-configuration-3.0.xsd"
		version="3.0">

	<default-provider>com.acme.ValidationProvider</default-provider>

	<message-interpolator>com.acme.MessageInterpolator</message-interpolator>
	<traversable-resolver>com.acme.TraversableResolver</traversable-resolver>
	<constraint-validator-factory>
		com.acme.ConstraintValidatorFactory
	</constraint-validator-factory>
	<parameter-name-provider>com.acme.ParameterNameProvider</parameter-name-provider>
	<clock-provider>com.acme.ClockProvider</clock-provider>

	<value-extractor>com.acme.ContainerValueExtractor</value-extractor>

	<executable-validation enabled="true">
		<default-validated-executable-types>
			<executable-type>CONSTRUCTORS</executable-type>
			<executable-type>NON_GETTER_METHODS</executable-type>
			<executable-type>GETTER_METHODS</executable-type>
		</default-validated-executable-types>
	</executable-validation>

	<constraint-mapping>META-INF/validation/constraints-car.xml</constraint-mapping>

	<property name="hibernate.validator.fail_fast">false</property>
</validation-config>

=== hibernate/hibernate-validator/tck-runner/src/test/resources/org/hibernate/validator/tckrunner/securitymanager/debug/validation-BootstrapConfigurationTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Jakarta Bean Validation TCK

    License: Apache License, Version 2.0
    See the license.txt file in the root directory or <http://www.apache.org/licenses/LICENSE-2.0>.

-->
<validation-config
        xmlns="https://jakarta.ee/xml/ns/validation/configuration"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://jakarta.ee/xml/ns/validation/configuration validation-configuration-3.0.xsd"
        version="3.0">
        
            <default-provider>com.acme.ValidationProvider</default-provider>
            <message-interpolator>com.acme.MessageInterpolator</message-interpolator>
            <traversable-resolver>com.acme.TraversableResolver</traversable-resolver>
            <constraint-validator-factory>com.acme.ConstraintValidatorFactory</constraint-validator-factory>
            <parameter-name-provider>com.acme.ParameterNameProvider</parameter-name-provider>
            <constraint-mapping>mapping1</constraint-mapping>
            <constraint-mapping>mapping2</constraint-mapping>
            <property name="com.acme.Foo">Bar</property>
            <property name="com.acme.Baz">Qux</property>
</validation-config>
